{"name": "test_login_user_with_incorrect_login_and_password", "status": "passed", "description": "Проверка невозможности логина пользователя с неверным логином и паролем.Получаем ошибку 401", "steps": [{"name": "Логин пользователя в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'bbobrov@example.net', 'password': 'I4TM+4OosD', 'name': 'Зыкова Надежда Афанасьевна'}"}], "start": 1719740942569, "stop": 1719740943013}], "start": 1719740942533, "stop": 1719740943013, "uuid": "70ac8684-8da0-4ade-be1f-1d1d6782560a", "historyId": "3a1956904ff880a4bcd6a84684410a2b", "testCaseId": "3a1956904ff880a4bcd6a84684410a2b", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_incorrect_login_and_password", "labels": [{"name": "story", "value": "Ручка /api/auth/login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-MP25VCCB"}, {"name": "thread", "value": "11256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}