{"name": "Проверка невозможности логина пользователя с неверным логином и паролем.Получаем ошибку 401", "status": "passed", "description": "Авторизация пользователя", "steps": [{"name": "Логин пользователя в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'feliksodintsov@example.org', 'password': '!Yu3v5Qbe6', 'name': 'Евдокимов Борислав Фролович'}"}], "start": 1720008886356, "stop": 1720008886445}], "start": 1720008886313, "stop": 1720008886446, "uuid": "804ff442-7b37-4feb-a4b1-c42877846246", "historyId": "3a1956904ff880a4bcd6a84684410a2b", "testCaseId": "3a1956904ff880a4bcd6a84684410a2b", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_incorrect_login_and_password", "labels": [{"name": "story", "value": "Ручка /api/auth/login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-MP25VCCB"}, {"name": "thread", "value": "4008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}